import test from 'node:test';
import assert from 'node:assert/strict';
import { readFilters, filterLibrary, paginateLibrary, pageWindow, filtersUrl } from '../src/lib/library.ts';
import fs from 'node:fs';
const base={id:'a',title:'Agent 记忆',description:'权限与撤权实验',tags:['MCP','记忆'],topics:['systems'],type:'essay',status:'growing',series:'memory',seriesTitle:'Agent 记忆设计',chapter:1,published:'2026-09-01',updated:'2026-09-05',minutes:5,readingTime:'5 min'};
const entries=[base,{...base,id:'b',title:'产品实践',description:'交付结果',topics:['practice'],tags:['产品'],series:'',seriesTitle:'',chapter:0,published:'2026-09-02',updated:'2026-09-04',minutes:8},{...base,id:'c',title:'检索策略',chapter:2,updated:'2026-09-06',minutes:4}];
const filters=changes=>({...readFilters(new URLSearchParams()),...changes});
test('default sorts by revision, without mutating input',()=>{const before=JSON.stringify(entries);assert.deepEqual(filterLibrary(entries,filters({})).map(x=>x.id),['c','a','b']);assert.equal(JSON.stringify(entries),before);});
test('Chinese query and all terms match summary',()=>assert.deepEqual(filterLibrary(entries,filters({q:'记忆 撤权'})).map(x=>x.id),['c','a']));
test('normalizes case, whitespace and full-width Latin',()=>assert.equal(filterLibrary(entries,filters({q:'  ＡＧＥＮＴ  ' })).length,2));
test('matches tags and series names',()=>assert.equal(filterLibrary(entries,filters({q:'MCP 设计'})).length,2));
test('combines exact topic, tag, series and type filters',()=>assert.equal(filterLibrary(entries,filters({topic:'systems',tag:'MCP',series:'memory',type:'essay'})).length,2));
test('conflicting filters return no matches',()=>assert.equal(filterLibrary(entries,filters({topic:'practice',series:'memory'})).length,0));
test('unknown URL filters do not silently show everything',()=>assert.equal(filterLibrary(entries,filters({tag:'missing'})).length,0));
test('standalone excludes series chapters',()=>assert.deepEqual(filterLibrary(entries,filters({scope:'standalone'})).map(x=>x.id),['b']));
test('series scope excludes independent articles',()=>assert.equal(filterLibrary(entries,filters({scope:'series'})).length,2));
test('selected series follows chapter order by default',()=>assert.deepEqual(filterLibrary(entries,filters({series:'memory'})).map(x=>x.chapter),[1,2]));
test('published and reading-time sorts work',()=>{assert.equal(filterLibrary(entries,filters({sort:'published'}))[0].id,'b');assert.equal(filterLibrary(entries,filters({sort:'shortest'}))[0].id,'c');});
test('pagination clamps invalid and out-of-range pages',()=>{const many=Array.from({length:25},(_,i)=>({...base,id:String(i)}));assert.equal(paginateLibrary(many,100).entries.length,1);assert.equal(paginateLibrary(many,-2).current,1);assert.equal(paginateLibrary(many,Infinity).current,1);assert.equal(paginateLibrary(many,2).entries[0].id,'12');});
test('empty results retain a valid page',()=>assert.deepEqual(paginateLibrary([],5),{entries:[],pages:1,current:1}));
test('shareable filters round-trip Unicode and special characters',()=>{const f=filters({q:'MCP & 记忆',tag:'AI 架构',page:3,sort:'shortest'});assert.deepEqual(readFilters(new URL(filtersUrl(f),'https://example.test').searchParams),f);});
test('pagination window stays bounded at thousands of pages',()=>assert.deepEqual(pageWindow(500,1000),[1,498,499,500,501,502,1000]));
test('registry has valid unique paths and chapter order matching reviewed series',()=>{
  const registry=JSON.parse(fs.readFileSync('src/data/knowledge.json','utf8'));
  const reviewed=JSON.parse(fs.readFileSync('docs/editorial-labs/series.json','utf8'));
  const ids=registry.series.flatMap(item=>item.articles);
  assert.equal(new Set(ids).size,ids.length);
  for(const id of ids) assert.ok(fs.existsSync(`src/content/writing/${id}.md`),id);
  for(const item of reviewed) assert.deepEqual(registry.series.find(series=>series.articles[0]===item.original).articles,item.articles.map(article=>article.slug));
});
